# version: '1.0'

# steps:
#   BuildingDockerImage:
#     title: Building Docker Image
#     type: build
#     image_name: freshkeep/fs-common-node
#     working_directory: ./
#     dockerfile: Dockerfile
#   RunningUnitTests:
#     title: Running Unit Tests
#     image: '${{BuildingDockerImage}}'
#     working_directory: IMAGE_WORK_DIR
#     entry_point:
#       - /bin/sh
#       - /codefresh/volume/cf-generated/unit_test_script
#     create_file:
#       path: /codefresh/volume/cf-generated
#       name: unit_test_script
#       content: |-
#         mkdir logs
#         npm install mocha -g --silent
#         npm install mocha-co -g --silent
#         npm install chai -g --silent
#         npm test
#     on_success:
#       metadata:
#         set:
#           - '${{BuildingDockerImage.imageId}}':
#               - CF_QUALITY: true
#     on_fail:
#       metadata:
#         set:
#           - '${{BuildingDockerImage.imageId}}':
#               - CF_QUALITY: false
#   DeployToNpm:
#     title: Publishing To Npm
#     image: codefresh/npm-publish:master
#     commands:
#       - NPM_TOKEN=${{NPM_TOKEN}} npm run ci-publish
#     when:
#       branch:
#         only: [ master ]
